name: Build and validate on MR

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Installing deps
        run: yarn

      - name: Linting
        run: yarn run lint

      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn run test
